// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRIABghwrctquqiG6KafaML6dsXO5ncw',
    appId: '1:51077541287:web:5c8922af1bac2dcf91da82',
    messagingSenderId: '51077541287',
    projectId: 'esante-bronchite',
    authDomain: 'esante-bronchite.firebaseapp.com',
    storageBucket: 'esante-bronchite.firebasestorage.app',
    measurementId: 'G-4FM3B6Q2N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZdj0xmTOhX1CNHYyn015CXL7Uc3jKHw',
    appId: '1:51077541287:android:e6fe915505e89ee691da82',
    messagingSenderId: '51077541287',
    projectId: 'esante-bronchite',
    storageBucket: 'esante-bronchite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYBHdBQu-s7UsEUgVmeRmOdZ8VFmhgJ9E',
    appId: '1:51077541287:ios:71616dff252e7d9491da82',
    messagingSenderId: '51077541287',
    projectId: 'esante-bronchite',
    storageBucket: 'esante-bronchite.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYBHdBQu-s7UsEUgVmeRmOdZ8VFmhgJ9E',
    appId: '1:51077541287:ios:71616dff252e7d9491da82',
    messagingSenderId: '51077541287',
    projectId: 'esante-bronchite',
    storageBucket: 'esante-bronchite.firebasestorage.app',
    iosBundleId: 'com.example.monProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsRIABghwrctquqiG6KafaML6dsXO5ncw',
    appId: '1:51077541287:web:059a427fc6f803f091da82',
    messagingSenderId: '51077541287',
    projectId: 'esante-bronchite',
    authDomain: 'esante-bronchite.firebaseapp.com',
    storageBucket: 'esante-bronchite.firebasestorage.app',
    measurementId: 'G-76NX8TDXPH',
  );
}
